# Generated by Django 4.2.11 on 2026-04-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_recipe_rating_reciperating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("text", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="home.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
