# Generated by Django 4.2.11 on 2026-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pantry_context',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
