# Generated by Django 4.2.11 on 2026-04-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mealplan'),
        ('home', '0007_chatsession_pantry_context'),
    ]

    operations = [
    ]
