# Generated by Django 4.2.11 on 2026-04-16 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_0006_mealplan_0007_chatsession_pantry_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('tag_type', models.CharField(choices=[('dietary', 'Dietary'), ('cuisine', 'Cuisine'), ('cooktime', 'Cook Time'), ('meal', 'Meal Type'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='home.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tags', to='home.tag')),
            ],
            options={
                'unique_together': {('recipe', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', through='home.RecipeTag', to='home.tag'),
        ),
    ]
