# Generated by Django 4.2.11 on 2026-04-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_seed_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/images/"),
        ),
    ]
