# Generated by Django 4.2.11 on 2026-04-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_seed_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="carbs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="fat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="protein",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
