# Generated by Django 4.2.11 on 2026-04-19 22:08

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=home.models.Recipe.recipe_image_path
            ),
        ),
    ]
