# Generated by Django 4.2.11 on 2026-04-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_mealplan_calories_mealplan_carbs_mealplan_fat_and_more'),
        ('home', '0012_recipe_favorites'),
    ]

    operations = [
    ]
