# Generated by Django 4.2.11 on 2026-04-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment'),
        ('home', '0013_merge_20260420_0415'),
    ]

    operations = [
    ]
