# Generated by Django 4.2.11 on 2026-04-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_recipe_favorites"),
        ("home", "0013_alter_recipe_image"),
    ]

    operations = []
