# Generated by Django 4.2.11 on 2026-04-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_merge_0012_recipe_favorites_0013_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
