# Generated by Django 4.2.11 on 2026-04-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_merge_20260420_0415"),
        ("home", "0015_recipe_description"),
    ]

    operations = []
