# Generated by Django 4.2.11 on 2026-04-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_comment_parent"),
        ("home", "0016_merge_20260420_2231"),
    ]

    operations = []
