# Generated by Django 4.2.11 on 2026-04-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='created_date',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-04-24T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='meal_plans', to='home.recipe'),
        ),
    ]
