# Generated by Django 4.2.11 on 2026-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="recipe_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
