# Generated by Django 4.2.11 on 2026-04-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_mealplan_recipe_data"),
        ("home", "0020_userstreak"),
    ]

    operations = []
