name: Code Lint

on: 
  pull_request: 
    branches: [main]
    types: [opened, synchronize, reopened] 
permissions: 
  contents: read 
  pull-requests: write 
jobs: 
  code_lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Pull Repository 
        uses: actions/checkout@v4 
      - name: Install Python
        uses: actions/setup-python@v6 
        with: 
          python-version: '3.12.3'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 
          pip install flake8 black
      - name: Run codebase through Black Formatter
        continue-on-error: true
        run: |
          set +e
          black --check --extend-exclude '/migrations/' . > black_results.txt 2>&1
          cat black_results.txt
          echo $? > black_exit_code.txt
          exit 0
      - name: Run codebase through flake8
        continue-on-error: true
        run: |
          set +e
          flake8 --output-file=flake8_results.txt .
          echo $? > flake8_exit_code.txt
          exit 0
      - name: Create Comment Formatting
        if: github.event_name == 'pull_request' && always()
        run: |
          {
            echo "## Linting Results"
            echo ""
            echo "### Black (Formatting)"
            if [ "$(cat black_exit_code.txt)" -ne 0 ]; then
              echo '```'
              echo "❌ Black formatter issues detected (run \`black .\` locally)"
              cat black_results.txt
              echo '```'
            else
              echo '```'
              echo "✅ Code is properly formatted"
              echo '```'
            fi
            echo ""
            echo "### Flake8 (Linting)"
            if [ "$(cat flake8_exit_code.txt)" -ne 0 ]; then
              echo '```'
              echo "❌ flake8 issues detected, please review the following"
              cat flake8_results.txt
              echo '```'
            else
              echo '```'
              echo "✅ No flake8 issues found"
            fi 
          } > pr-comment.txt
      - name: Create PR Comment
        if: github.event_name == 'pull_request' && always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'code-lint'
          path: pr-comment.txt
      - name: Fail workflow if linting failed
        if: always()
        run: |
          if [ "$(cat black_exit_code.txt)" -ne 0 ] || [ "$(cat flake8_exit_code.txt)" -ne 0 ]; then
            echo "Linting failed."
            exit 1
          fi
      - name: Clean up temporary files
        if: always()
        run: |
          rm -f flake8_results.txt pr-comment.txt black_results.txt
