name: Code Flake on Existing Code

on: 
  pull_request: 
    types: [opened, synchronize, reopened] 
  workflow_dispatch:
permissions: 
  contents: read 
  pull-requests: write 
jobs: 
  code_lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Pull Repository 
        uses: actions/checkout@v4 
        with: 
          fetch-depth: 2 
      - name: Install Python
        uses: actions/setup-python@v6 
        with: 
          python-version: '3.12.3'
      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install -r requirements.txt 
          pip install flake8
      - name: Run codebase through flake8
        if: always()
        run: |
          ls -a
          flake8 --show-source --count --output-file=flake8_results.txt dev1_cust7 
      - name: Put Lint Results in PR Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: flake8_results.txt
      - name: Clean up temporary file
        run: |
          rm flake8_results.txt
          
          
